apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tomcat
  namespace: flux-system
spec:
  releaseName: tomcat
  targetNamespace: default
  interval: '30s'
  chart:
    spec:
      chart: './Applicationset/charts/core-apps/tomcat'
      sourceRef:
        kind: GitRepository
        name: core-apps
        namespace: flux-system
