apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: core-apps
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/tanmay-bhat/ArgoCD
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/Applicationset/charts/core-apps/ 
