apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tomcat
  namespace: flux-system
spec:
  interval: '30s'
  chart:
    spec:
      chart: './Applicationset/charts/core-apps/tomcat'
      sourceRef:
        kind: GitRepository
        name: test
        namespace: flux-system
  values:
    replicaCount: 2



  # chart:
  #   git: git@github.com:tanmay-bhat/ArgoCD.git
  #   path: Applicationset/charts/core-apps
  #   ref: main



